### ISSUE TITLE
This line breaks when few data is passed with not enough variations

### ISSUE THREAD

**Issue by momegas** [squaredev-io/whitebox#47]
https://github.com/squaredev-io/whitebox/blob/2289186ed839c97c562dd6b2d678d6d5747740bc/src/analytics/metrics/pipelines.py#L104-L105

**Comment by NickNtamp** [comment]
The source of the bug was found:

During the construction of the confusion matrix, if all the predicted values are correct compared to the ground truth, the functions has no clue about the number of classes leading to incorrect calculations.

There is an easy fix on this, by adding the labels in the confusion matrix parameters.
