### ISSUE TITLE
[Roadmap] Publish docs site

### ISSUE THREAD

**Issue by momegas** [squaredev-io/whitebox#62]
- [x] #67
- [x] #68
- [x] #69
- [x] #70
- [x] #71

I propose we use [MKDocs Material](https://squidfunk.github.io/mkdocs-material/)

**Comment by momegas** [comment]
A very nice example is [FastAPI](https://fastapi.tiangolo.com/)

**Comment by momegas** [comment]
- Whitebox
    - A brief intro of Whitebox and what it does with logo and a brief mention of Squaredev
- Features
    - A nice list of features
        - Model monitoring / versioning
        - Pythonic style
        - Kuberneted first
- ML Monitoring intro
    - Explain what is ML monitoring and where it stands in MLOps
- Tutorial - user guide
    - Step by step detailed guide with examples on how to use WB
- Deployment
    - How to deploy whitebox via docker

**Comment by stavrostheocharis** [comment]
We will split some parts with @NickNtamp in order to contribute

**Comment by momegas** [comment]
Do we have any draft content on this one?

**Comment by sinnec** [comment]
There's the tutorials and SDK docs in https://github.com/squaredev-io/whitebox/pull/79

**Comment by NickNtamp** [comment]
Please review the docs under metrics and new glossary sections [here](https://github.com/squaredev-io/whitebox/pull/95).

There is a pending section regarding explainability. As it is a bit more tricky I would propose an indicative structure below and we could create a new task regarding this. Actually, not exactly structure but what I think that this chapter should include. 

----------------------------------------------------------

**1.1 Explain the confidence levels here.** 
 

> Level0: Explain a model trained in the client's training data. 

> Level1: Explain a model trying to predict the predictions of clients model. (no extensive analysis as this is pending)

> Level2: Explain client's model. (no extensive analysis as this is pending)

 
**1.2 Level0 Confidence level.**
 

> Talk a bit about the trained model (lightgbm)

**_QUESTIONS_**
  

> - What will be the name of this model? It is NOT a [surrogate model](https://deepchecks.com/glossary/surrogate-model/) in this stage. Surrogate model title is a more appropriate title for Level1 confidence. For instance we can call it baseline model or mimic model.
> - Will we talk about the evaluation metrics of the model?
> - Will the client have access to the evaluation metrics of the model?
> - Will we mention fine-tuning as a pending enhancement here?

> Talk about explainability feature. (LIME) Explain how it calculates the contribution of each feature to the final prediction. It is preferable here to avoid naming this as Feature Importance. [Feature Importance](https://towardsdatascience.com/how-to-utilize-feature-importance-correctly-1f196b061192) is used mainly as a predecessor step of feature selection during the dimensionality reduction.  

 
**1.3 Level1 Confidence level. (Leave this as pending)**
 
**1.4 Level2 Confidence level. (leave this as pending)**

----------------------------------------------------------

Please respond in an explicit manner to the above questions and let me know if you agree or not with the structure, in order to avoid any misunderstandings and back-and-forth. Thank you in advance. 
cc: @momegas , @stavrostheocharis

**Comment by stavrostheocharis** [comment]
Some remarks from my side:

- The structure looks fine to me
- "What will be the name of this model? It is NOT a [surrogate model](https://deepchecks.com/glossary/surrogate-model/) in this stage. Surrogate model title is a more appropriate title for Level1 confidence. For instance we can call it baseline model or mimic model."
-> I agree on that. Maybe simple model, baseline model, or replacement-model (or something like that) as you suggested Niko
- "Will we talk about the evaluation metrics of the model?", "Will the client have access to the evaluation metrics of the model?"
-> I believe that we should provide this kind of metrics, so that the user will be able to know if she should or should not trust the explanations. So we should mention this kind of evaluation metrics
- "Will we mention fine-tuning as a pending enhancement here?"
-> Again, yes that it will follow as an implementation based on our roadmap
- "Talk about explainability feature. (LIME) Explain how it calculates the contribution of each feature to the final prediction. It is preferable here to avoid naming this as Feature Importance. [Feature Importance](https://towardsdatascience.com/how-to-utilize-feature-importance-correctly-1f196b061192) is used mainly as a predecessor step of feature selection during the dimensionality reduction."
-> Also agree with that. Mention that currently Lime is used

**Comment by NickNtamp** [comment]
@momegas I believe that there is some pending work in the main Feature page of docs:
- I don't know if is too early to add regression there
- Data drift should be the correct term (model drift should be removed). Also we have to add Concept drift
- We have to add the explainability feature

**Comment by NickNtamp** [comment]
I will!
